### PR TITLE
Remove globbing

### PR DESCRIPTION
**Pull request by rusko124**
Discussion about the problem here #13 .

### CODE REVIEW

**Comment by vpetersson** [comment]
@renat-galimov I'm ready to merge as soon as you OK it.

**Comment by renat-galimov** [comment]
Does it work? Did you try the resulting file on Screenly Pro?

**Comment by rusko124** [comment]
@renat-galimov Not yet, I ping you after I checked.

**Comment by rusko124** [comment]
I have tested but still the problem if the renderer is NetworkManager. I continue to solve the problem.

**Comment by rusko124** [comment]
@renat-galimov 
These edits still work, but need to enable ethernet support for network-manager.
See https://docs.ubuntu.com/core/en/stacks/network/network-manager/docs/reference/configuration/ethernet_support

**Comment by renat-galimov** [comment]
@rusko124, thanks. 

Please don't merge the changes until Screenly version 2 player is not updated.

**Comment by renat-galimov** [comment]
@vpetersson, you can land it.

**Pull request merged**
